version = 0.1

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "todo-list-aws-production"
s3_bucket = "cp1-d-julian-sanchez-alcazar"
s3_prefix = "todo-list-aws-production"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
confirm_changeset = false
allow_no_authentication = true
disable_rollback = false




